vim.g.mapleader = " "
vim.g.maplocaleader = " "
vim.opt.nu = true
vim.opt.relativenumber = true
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.smartindent = true
vim.opt.smartcase = true
vim.opt.wrap = false
vim.opt.swapfile = false
vim.opt.backup = false
vim.opt.undodir = vim.fn.stdpath("data") .. "/.vim/undodir"
vim.opt.undofile = true
vim.opt.hlsearch = false
vim.opt.incsearch = true
vim.opt.scrolloff = 20
vim.opt.signcolumn = "yes"
vim.opt.isfname:append("@-@")
vim.opt.clipboard = "unnamedplus"
vim.opt.updatetime = 50
vim.opt.conceallevel = 2
vim.opt.statusline = "no"
vim.opt.termguicolors = true
vim.opt.shell = vim.loop.os_uname().sysname:lower():find("windows") and "pwsh.exe" or os.getenv("SHELL")
vim.opt.winborder = "rounded"

vim.keymap.set("n", "<leader>bn", "<cmd>bnext<CR>", { desc = "Go to next buffer" })
vim.keymap.set("n", "<leader>bp", "<cmd>bprevious<CR>", { desc = "Go to previous buffer" })
vim.keymap.set("n", "<leader>bd", "<cmd>bdelete<CR>", { desc = "Delete current buffer" })
vim.keymap.set("n", "<C-s>", "<cmd>w<CR>", { desc = "Save current buffer to file" })
vim.keymap.set("n", "<C-D-h>", "<C-w>left", { desc = "Move to left split" })
vim.keymap.set("n", "<C-D-j>", "<C-w>down", { desc = "Move to down split" })
vim.keymap.set("n", "<C-D-k>", "<C-w>up", { desc = "Move to up split" })
vim.keymap.set("n", "<C-D-l>", "<C-w>right", { desc = "Move to right split" })
