require("vim._core.ui2").enable({})
require("core.options")
require("core.keymaps")
require("core.ui")
require("core.reload")
-- require("core.statusline")
require("core.autocmd")
require("core.floating-terminal")
require("plugins")
-- pcall(require, "user.options")
-- pcall(require, "user.keymaps")
-- pcall(require, "user.plugins")
