require("core.options")
require("core.keymaps")
require("core.ui")
require("core.reload")
require("core.statusline")
require("core.aucmd")
require("core.floating-terminal")
require("plugins")
-- require("lsp")
pcall(require, "user.options")
pcall(require, "user.keymaps")
pcall(require, "user.plugins")
